"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-22 11:31:15.522637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("actor", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jd_configs",
        sa.Column("jd_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("ai_suggestion", sa.Text(), nullable=True),
        sa.Column("final", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("jd_id", "version"),
    )
    op.create_table(
        "jds",
        sa.Column("jd_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("text_hash", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("jd_id"),
    )
    op.create_index(op.f("ix_jds_text_hash"), "jds", ["text_hash"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("done", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "llm_cache",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "manual_evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.String(), nullable=True),
        sa.Column("skill", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manual_evidence_profile_id"), "manual_evidence", ["profile_id"], unique=False
    )
    op.create_table(
        "match_results",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("verdict", sa.String(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", "profile_id"),
    )
    op.create_index(
        op.f("ix_match_results_match_score"), "match_results", ["match_score"], unique=False
    )
    op.create_index(op.f("ix_match_results_verdict"), "match_results", ["verdict"], unique=False)
    op.create_table(
        "match_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("jd_id", sa.String(), nullable=True),
        sa.Column("jd_version", sa.Integer(), nullable=True),
        sa.Column("weights", sa.Text(), nullable=True),
        sa.Column("weights_hash", sa.String(), nullable=True),
        sa.Column("taxonomy_version", sa.String(), nullable=True),
        sa.Column("equivalence_version", sa.String(), nullable=True),
        sa.Column("models", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_match_runs_jd_id"), "match_runs", ["jd_id"], unique=False)
    op.create_table(
        "pii_map",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table(
        "profiles",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("lane", sa.String(), nullable=True),
        sa.Column("total_exp", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("parsed_at", sa.String(), nullable=True),
        sa.Column("parser_model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("retain_until", sa.String(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_index(op.f("ix_profiles_file_hash"), "profiles", ["file_hash"], unique=False)
    op.create_table(
        "review_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("profile_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("new_verdict", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(), nullable=True),
        sa.Column("at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_actions_profile_id"), "review_actions", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_review_actions_run_id"), "review_actions", ["run_id"], unique=False)
    op.create_table(
        "skill_equivalence",
        sa.Column("skill_a", sa.String(), nullable=False),
        sa.Column("skill_b", sa.String(), nullable=False),
        sa.Column("relation", sa.String(), nullable=True),
        sa.Column("factor", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("review_status", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("skill_a", "skill_b"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_equivalence")
    op.drop_index(op.f("ix_review_actions_run_id"), table_name="review_actions")
    op.drop_index(op.f("ix_review_actions_profile_id"), table_name="review_actions")
    op.drop_table("review_actions")
    op.drop_index(op.f("ix_profiles_file_hash"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("pii_map")
    op.drop_index(op.f("ix_match_runs_jd_id"), table_name="match_runs")
    op.drop_table("match_runs")
    op.drop_index(op.f("ix_match_results_verdict"), table_name="match_results")
    op.drop_index(op.f("ix_match_results_match_score"), table_name="match_results")
    op.drop_table("match_results")
    op.drop_index(op.f("ix_manual_evidence_profile_id"), table_name="manual_evidence")
    op.drop_table("manual_evidence")
    op.drop_table("llm_cache")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_jds_text_hash"), table_name="jds")
    op.drop_table("jds")
    op.drop_table("jd_configs")
    op.drop_table("deletions")
    # ### end Alembic commands ###
